/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daiSol from "./DAI.sol";
export type { daiSol };
import type * as dewSol from "./DEW.sol";
export type { dewSol };
export type { Vulcan } from "./Vulcan";
export type { VulcanPadFactory } from "./VulcanPadFactory";
